baseURL = 'http://example.org/'
languageCode = 'en-us'
title = "Michał's website"
theme = "cactus"


[params]
	showAllPostsOnHomePage = true
	postsOnHomePage = 5 # this option will be ignored
	mainSection = "posts"
	description = "Hi I'm Michał and this is my corner of the Internet. Enjoy :)"
	showAllPostsOnHomePage = true
	colortheme = "light"
	showprojectslist = true
	tagsoverview = true

[[params.social]]
	name = "github"
	link = "https://github.com/MichalThx"

[[params.social]]
	name = "email"
	link = "me@michalszwedo.com"


[[menu.main]]
	name = "Home"
	url = "/"
	weight = 1

[[menu.main]]
	name = "All posts"
	url = "/posts"
	weight = 2

[[menu.main]]
	name = "Tags"
	url = "/tags"
	weight = 3

[[menu.main]]
	name = "About"
	url = "/about"
	weight = 4

[taxonomies]
	tag = "tags"
	category = "categories"